### PR TITLE
Fix uname return value condition for Illumos

### PR DESCRIPTION
**Pull request by messense**
https://illumos.org/man/2/uname

> Upon successful completion, a non-negative value is returned. Otherwise,
> -1 is returned and errno is set to indicate the error.

Other platforms:

1. [Linux](https://man7.org/linux/man-pages/man2/uname.2.html): On success, zero is returned.  On error, -1 is returned, and errno is set to indicate the error.
2. [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=uname&sektion=3&n=1): The uname() function returns the value 0 if successful; otherwise the value -1 is returned and the global variable errno	is set to indicate the error.
3. [macOS](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/uname.3.html): The uname() function returns the value 0 if successful; otherwise the value -1 is returned and the global variable errno is set to indicate the error.
4. [Solaris](https://docs.oracle.com/cd/E86824_01/html/E54765/uname-2.html): Upon successful completion, a non-negative value is returned. Otherwise, −1 is returned and errno is set to indicate the error.

### CODE REVIEW

**Comment by sylvestre** [comment]
Could you please update the commit message ?
it is more about fixing an issue with illumos than porting it
thanks

**Comment by messense** [comment]
> Could you please update the commit message ? it is more about fixing an issue with illumos than porting it thanks

Done.

**Comment by messense** [comment]
A new release on crates.io would be great, thanks!

**Comment by sylvestre** [comment]
Yeah, I am working on polishing this crate a bit :)
https://github.com/uutils/platform-info/pull/17

**Comment by sylvestre** [comment]
Done: 
https://crates.io/crates/platform-info/0.2.0

**Pull request merged**
