### PR TITLE
tests ~ add fail point instrumentation/testing (coverage => 100%)

### PR DESCRIPTION
**Pull request by rivy**
As promised, [full test coverage](https://app.codecov.io/github/rivy/rs.platform-info/commit/da12b2fd80037b4928793f29513c14bda6c2b81d)!

- improves testing code coverage to 100%
- includes:
  - test polish
  - fail_point instrumentation
  - serialization of all tests using fail_point manipulation (relative to each other and all other tests)
    - b/c fail_points are global/shared structures and RACY
  - `function_name` macros used to standardize naming of fail_points

ToDO?: reduce fail_point configuration and use boilerplate code with macro/macros?

### CODE REVIEW

**Comment by sylvestre** [comment]
tbh, I am not convinced, it is making the code harder to read (and probably bigger code ?) for a tiny benefit

**Comment by rivy** [comment]
@sylvestre @tertsdiepraam 

I'm interested in opinions about these code changes.

Instrumentation like this is the only way that I know of to fully test the use of OS/externally-controlled functions, especially failure conditions. But it adds three direct dependencies and a large number of secondary dependencies, as well as some necessary configuration and use boilerplate code.

Compile time is obviously longer but not really significantly longer in comparison to other crates.

It was a fun exercise, and I'll definitely keep a branch copy within my repo/fork for reference, no matter whether we use it.

Your thoughts?

**Comment by sylvestre** [comment]
(i was negative in my tone but i loved your experiment to get 100% :)

**Comment by sylvestre** [comment]
given we are quite high, i don't think we want to increase the complexity in the code
` codecov/project 94.97% (+0.00%) compared to dc1dbb0 `

**Pull request closed without merging**
